/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import * as msRest from "@azure/ms-rest-js";


export const TaskItem: msRest.CompositeMapper = {
  serializedName: "TaskItem",
  type: {
    name: "Composite",
    className: "TaskItem",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      title: {
        serializedName: "title",
        type: {
          name: "String"
        }
      },
      status: {
        serializedName: "status",
        type: {
          name: "Number"
        }
      },
      createdDate: {
        serializedName: "createdDate",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const TodoItem: msRest.CompositeMapper = {
  serializedName: "TodoItem",
  type: {
    name: "Composite",
    className: "TodoItem",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      title: {
        serializedName: "title",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      dueDate: {
        serializedName: "dueDate",
        type: {
          name: "DateTime"
        }
      },
      status: {
        serializedName: "status",
        type: {
          name: "Number"
        }
      },
      subTasks: {
        serializedName: "subTasks",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "TaskItem"
            }
          }
        }
      },
      createdDate: {
        serializedName: "createdDate",
        type: {
          name: "DateTime"
        }
      }
    }
  }
};

export const TaskItemReq: msRest.CompositeMapper = {
  serializedName: "TaskItemReq",
  type: {
    name: "Composite",
    className: "TaskItemReq",
    modelProperties: {
      title: {
        serializedName: "title",
        type: {
          name: "String"
        }
      },
      status: {
        serializedName: "status",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const AddTodoItemReq: msRest.CompositeMapper = {
  serializedName: "AddTodoItemReq",
  type: {
    name: "Composite",
    className: "AddTodoItemReq",
    modelProperties: {
      title: {
        serializedName: "title",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      dueDate: {
        serializedName: "dueDate",
        type: {
          name: "DateTime"
        }
      },
      status: {
        serializedName: "status",
        type: {
          name: "Number"
        }
      },
      subTasks: {
        serializedName: "subTasks",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "TaskItemReq"
            }
          }
        }
      }
    }
  }
};

export const UpdateTodoItemReq: msRest.CompositeMapper = {
  serializedName: "UpdateTodoItemReq",
  type: {
    name: "Composite",
    className: "UpdateTodoItemReq",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      title: {
        serializedName: "title",
        type: {
          name: "String"
        }
      },
      description: {
        serializedName: "description",
        type: {
          name: "String"
        }
      },
      dueDate: {
        serializedName: "dueDate",
        type: {
          name: "DateTime"
        }
      },
      status: {
        serializedName: "status",
        type: {
          name: "Number"
        }
      },
      subTasks: {
        serializedName: "subTasks",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "TaskItemReq"
            }
          }
        }
      }
    }
  }
};

export const UpdateTodoItemStatusReq: msRest.CompositeMapper = {
  serializedName: "UpdateTodoItemStatusReq",
  type: {
    name: "Composite",
    className: "UpdateTodoItemStatusReq",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      },
      status: {
        serializedName: "status",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const DeleteTodoItemReq: msRest.CompositeMapper = {
  serializedName: "DeleteTodoItemReq",
  type: {
    name: "Composite",
    className: "DeleteTodoItemReq",
    modelProperties: {
      id: {
        serializedName: "id",
        type: {
          name: "Uuid"
        }
      }
    }
  }
};

export const AddTaskItemReq: msRest.CompositeMapper = {
  serializedName: "AddTaskItemReq",
  type: {
    name: "Composite",
    className: "AddTaskItemReq",
    modelProperties: {
      todoItemId: {
        serializedName: "todoItemId",
        type: {
          name: "Uuid"
        }
      },
      title: {
        serializedName: "title",
        type: {
          name: "String"
        }
      },
      status: {
        serializedName: "status",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const UpdateTaskItemReq: msRest.CompositeMapper = {
  serializedName: "UpdateTaskItemReq",
  type: {
    name: "Composite",
    className: "UpdateTaskItemReq",
    modelProperties: {
      todoItemId: {
        serializedName: "todoItemId",
        type: {
          name: "Uuid"
        }
      },
      taskItemId: {
        serializedName: "taskItemId",
        type: {
          name: "Uuid"
        }
      },
      title: {
        serializedName: "title",
        type: {
          name: "String"
        }
      },
      status: {
        serializedName: "status",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const UpdateTaskItemStatusReq: msRest.CompositeMapper = {
  serializedName: "UpdateTaskItemStatusReq",
  type: {
    name: "Composite",
    className: "UpdateTaskItemStatusReq",
    modelProperties: {
      todoItemId: {
        serializedName: "todoItemId",
        type: {
          name: "Uuid"
        }
      },
      taskItemId: {
        serializedName: "taskItemId",
        type: {
          name: "Uuid"
        }
      },
      status: {
        serializedName: "status",
        type: {
          name: "Number"
        }
      }
    }
  }
};

export const DeleteTaskItemReq: msRest.CompositeMapper = {
  serializedName: "DeleteTaskItemReq",
  type: {
    name: "Composite",
    className: "DeleteTaskItemReq",
    modelProperties: {
      taskItemId: {
        serializedName: "taskItemId",
        type: {
          name: "Uuid"
        }
      },
      todoItemId: {
        serializedName: "todoItemId",
        type: {
          name: "Uuid"
        }
      }
    }
  }
};
